routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/home',['as'=>'dashboard','uses'=>'HomeController@index']);
Route::get('/typography',['as'=>'typography','uses'=>'HomeController@typography']);
Route::get('/helper',['as'=>'helper','uses'=>'HomeController@helper']);
Route::get('/widget',['as'=>'widget','uses'=>'HomeController@widget']);
Route::get('/table',['as'=>'table','uses'=>'HomeController@table']);
Route::get('/media',['as'=>'media','uses'=>'HomeController@media']);
Route::get('/chart',['as'=>'chart','uses'=>'HomeController@chart']);
Route::get('/form',['as'=>'form','uses'=>'HomeController@form']);
 
Route::group(['middleware'=>['auth']],function(){
        // Route::get('/home',function(){
        //         return view('index');
        // });
        Route::group(['prefix'=>'learn-vue','namespace'=>'Dashboard'],function(){
              Route::get('/',['uses'=>'LearnVueController@index']);
        });
        
        Route::get('/home',['as'=>'dashboard','uses'=>'HomeController@index']);
        Route::group(['middleware' => ['role:admin']], function () {
                Route::resource('permissions', 'Admin\PermissionsController');     
                Route::resource('roles', 'Admin\RolesController');     
                Route::resource('users', 'Admin\UsersController'); 
                Route::resource('add-items', 'Admin\AddItemController');  
            });
        
        Route::resource('profile','Users\ProfileController');
});

Route::get('/',['as'=>'transaksi.index.view','uses'=>'Dashboard\TransaksiController@indexView']);
Route::get('/transaksi-data-api',['uses'=>'Dashboard\TransaksiController@index'])
        ->name('transaksi.index.api');
Route::get('/transaksi-product-data-api',['uses'=>'Dashboard\TransaksiController@allProduct'])
        ->name('transaksi.product.index.api');

app/Http/Controllers/Admin/AddItemController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Item; 
use Auth;

class AddItemController extends Controller
{
     /**
    *
    * allow admin only
    *
    */

    public function __construct() {
        $this->middleware('role:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $items = Item::all();
        return view('admin.add-items.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.add-items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name'  => 'required',
            'description' => 'required',
            'item_image' => 'required',
            'price' => 'required'
        ]);

        $name = 'null';
        $newImageName = 'null';
        
        //check if file attached
        if($file = $request->file('item_image')){
            $tmp = explode('.', $file->getClientOriginalName());//get client file name
            $name = $file->getClientOriginalName();
            $newImageName = round(microtime(true)).'.'.end($tmp);
            $file->move(storage_path('app\public\products'), $newImageName);          
        }

        Item::create(array_merge($request->all(),['item_image' => $newImageName, 'user_id' => Auth::user()->id]));

        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $item = Item::findOrFail($id);

        return view('admin.add-items.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'name'  => 'required',
            'description' => 'required',
            'price' => 'required'
        ]);

        $name = 'null';
        $newImageName = 'null';
        
        //check if file attached
        if($file = $request->file('item_image')){
            $tmp = explode('.', $file->getClientOriginalName());//get client file name
            $name = $file->getClientOriginalName();
            $newImageName = round(microtime(true)).'.'.end($tmp);
            $file->move(storage_path('app\public\products'), $newImageName);          
        }

        $newImage = 'null';
        $newImage = $newImageName == 'null'? Item::find($id)->item_image:$newImageName;

        $item = Item::findOrFail($id);
        $item->update(array_merge($request->all(),['item_image' => $newImage]));

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $item = Item::findOrFail($id);
        $item->delete();
        return redirect()->back();
    }
}

resources/views/admin/add-items/index.blade.php
@extends('index')

@section('title')
	Jewellery
@endsection

@section('extra-css')
<!-- Colorpicker Css -->
    {{ Html::style('bsbmd/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css') }}

    <!-- Dropzone Css -->
    {{ Html::style('bsbmd/plugins/dropzone/dropzone.css') }}

    <!-- Multi Select Css -->
    {{ Html::style('bsbmd/plugins/multi-select/css/multi-select.css') }}

    <!-- Bootstrap Spinner Css -->
    {{ Html::style('bsbmd/plugins/jquery-spinner/css/bootstrap-spinner.css') }}

    <!-- Bootstrap Tagsinput Css -->
    {{ Html::style('bsbmd/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css') }}

    <!-- Bootstrap Select Css -->
    {{ Html::style('bsbmd/plugins/bootstrap-select/css/bootstrap-select.css') }}

    <!-- noUISlider Css -->
    {{ Html::style('bsbmd/plugins/nouislider/nouislider.min.css') }}

     <!-- JQuery DataTable Css -->
    {{ Html::style('bsbmd/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}
	
@endsection

@section('content')
        <div class="container-fluid">
            <div class="block-header">
                <h2>Add Items</h2>
            </div>

            <!-- Vertical Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header bg-pink">
                            <h2>Add Items</h2>
                            <a href="{{route('add-items.create')}}" class="btn btn-info m-t-15 waves-effect">Add New</a>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">                        	
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                        	<th>Id</th>
                                            <th>name</th>
                                            <th>Item Image</th>
                                            <th>Net wt</th>
                                            <th>Gross wt</th>
                                            <th>Stone wt</th>
                                            <th>Other Details</th>
                                            <th>Description</th>
                                            <th>Caret</th>
                                            <th>Item_size</th>
                                            <th>Purity</th>
                                            <th>Height</th>
                                            <th>Width</th>
                                            <th>Discount</th>
                                            <th>Price</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                        	<th>Id</th>
                                            <th>name</th>
                                            <th>Item Image</th>
                                            <th>Net wt</th>
                                            <th>Gross wt</th>
                                            <th>Stone wt</th>
                                            <th>Other Details</th>
                                            <th>Description</th>
                                            <th>Caret</th>
                                            <th>Item_size</th>
                                            <th>Purity</th>
                                            <th>Height</th>
                                            <th>Width</th>
                                            <th>Discount</th>
                                            <th>Price</th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @if (count($items) > 0)
                                        	@foreach($items as $row)
                                            <tr>                                        	
                                            	<td>{{ $row->id }}</td>
                                                <td>{{ $row->name }} </td>
                                                <td>
                                                    <img src="{{url('storage/products',$row->item_image)}}" width="60" height="60" alt="{{ $row->name }}" />
                                                </td>
                                                <td>{{ $row->net_wt }} </td>
                                                <td>{{ $row->gross_wt }} </td>
                                                <td>{{ $row->stone_wt }} </td>
                                                <td>{{ $row->other_details }} </td>
                                                <td>{{ $row->description }} </td>
                                                <td>{{ $row->caret }} </td>
                                                <td>{{ $row->item_size }} </td>
                                                <td>{{ $row->purity }} </td>
                                                <td>{{ $row->height }} </td>
                                                <td>{{ $row->width }} </td>
                                                <td>{{ $row->discount }} </td>
                                                <td>{{ $row->price }} </td>
                                            	<td>
                                            		<a href="{{route('add-items.edit',$row->id)}}" class="btn btn-warning waves-effect">Edit</a>
                                            	</td>
                                            	<td>
                                            		<form id="delete_form" method="POST" action="{{ route('add-items.destroy',$row->id) }}">
    					                            	{{ csrf_field() }}
    					                            	<input name="_method" type="hidden" value="DELETE">
    					                                <button class="btn btn-danger waves-effect" type="submit">Delete</button>
    					                            </form>
                                            	</td>	                                   
                                            </tr>
                                            @endforeach
                                        @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Vertical Layout -->
           
        </div>
@endsection

@section('extra-script')
	{{Html::script('bsbmd/plugins/autosize/autosize.js')}}
	{{Html::script('bsbmd/plugins/momentjs/moment.js')}}
	{{Html::script('bsbmd/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')}}
	{{Html::script('bsbmd/js/pages/forms/basic-form-elements.js')}}	
    {{Html::script('bsbmd/plugins/jquery-validation/jquery.validate.js')}}
    {{Html::script('bsbmd/plugins/jquery-steps/jquery.steps.js')}}
    {{Html::script('bsbmd/plugins/sweetalert/sweetalert.min.js')}}
    {{Html::script('bsbmd/js/pages/forms/form-validation.js')}}

    <!-- Jquery DataTable Plugin Js -->
    {{Html::script('bsbmd/plugins/jquery-datatable/jquery.dataTables.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/extensions/export/jszip.min.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}	
    {{Html::script('bsbmd/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}	
    {{Html::script('bsbmd/js/pages/tables/jquery-datatable.js') }}
@endsection